### ISSUE TITLE
I2c and sensors not working

### ISSUE THREAD

**Issue by hdowne** [travisfarmer/tjf_mcp23017#1]
Hello

I have a n scale train layout with current sensing block detection connected to an mcp23017 and an Arduino Uno. I have the detection working but I am unable to add more than about 10 sensors pins. I am using your DCC++ program. If I comment out the use_mcp_io line in the config files I can then add 20 - 30 sensors and save them to eeprom, but if I then add the use_mcp_io back in, I lose all sensors except the first 10 or so. The same problem happens if I use your tjf_mcp23017 or the adafruit_mcp23017 libraries. I hope you can help me find out what is happening. 

Thanks
Harold
Hdowne at Yahoo dot ca

**Comment by travisfarmer** [comment]
i had it working perfectly... now i keep getting a segmentation fault when compiling... very frusterating!

**Comment by travisfarmer** [comment]
ok, it works. my hardware prototype is a bit flakey, and apparently so is my compiler, somehow (Arduino 1.8.9). but it does seem to work. please try replacing your copy of the tjf_mcp23017 library with my copy (make a backup of your if you wish).
Also, make sure the MCP23017 reset pin is pulled high (mine was floating, hence my troubles).

Please let me know how you make out with it.

~Travis

**Comment by hdowne** [comment]
Hi Travis
Received mega and installed program and does seem to work on multiple MCP's, even the outputs for LEDs are working. I also received the TCA's and next step is to work on getting them working. I am also able to add upto 40 sensors and save to the eeprom.
Thanks also for the mention in the file for additional contributer.
Thanks again for your help.

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 1, 2019 at 17:28, Travis Farmer<notifications@github.com> wrote:   
ok, it works. my hardware prototype is a bit flakey, and apparently so is my compiler, somehow (Arduino 1.8.9). but it does seem to work. please try replacing your copy of the tjf_mcp23017 library with my copy (make a backup of your if you wish).
Also, make sure the MCP23017 reset pin is pulled high (mine was floating, hence my troubles).

Please let me know how you make out with it.

~Travis

**Comment by travisfarmer** [comment]
there is (was?) code for the TCAs commented out in the MCP library. i never tested it, but it may be a place to start. not a problem about the mention, i feel credit where credit is due.

~Travis
